#!/bin/bash

#Peticion 1: Mostrar Todos Los Usuario
curl -X GET http://localhost:8080/api/v1/users

#Peticion 2: Mostrar Todos Los Amigos De Un Usuario
curl -X GET http://localhost:8080/api/v1/user/friends -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZWFkLWxpbmUiOiJTYXQgTWF5IDI5IDEwOjE0OjI4IDIwMjEiLCJpZCI6IjYwYjFjNDkyNGFiMjkzZGU5NjFkYTBlNyIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiY2ZhYnJpY2E0NiIsInV1aWQiOiI3OWVhOGVjNi0xMmNhLTRjZjktYmFjYi0zOTBkODI4Yzg0YjEifQ.82ZvIygphY_-rzdk_nEF48ZOgfhwhxWzIXTRNU8cnTU"

#Peticion 3: Mostrar Todos Los Post De Un Usuario
curl -X GET http://localhost:8080/api/v1/user/posts -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZWFkLWxpbmUiOiJTYXQgTWF5IDI5IDEwOjE0OjI4IDIwMjEiLCJpZCI6IjYwYjFjNDkyNGFiMjkzZGU5NjFkYTBlNyIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiY2ZhYnJpY2E0NiIsInV1aWQiOiI3OWVhOGVjNi0xMmNhLTRjZjktYmFjYi0zOTBkODI4Yzg0YjEifQ.82ZvIygphY_-rzdk_nEF48ZOgfhwhxWzIXTRNU8cnTU"

#Peticion 4: Mostrar Post de un amigo
curl -X GET http://localhost:8080/api/v1/friend/arthuronavah/posts -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZWFkLWxpbmUiOiJTYXQgTWF5IDI5IDEwOjE0OjI4IDIwMjEiLCJpZCI6IjYwYjFjNDkyNGFiMjkzZGU5NjFkYTBlNyIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiY2ZhYnJpY2E0NiIsInV1aWQiOiI3OWVhOGVjNi0xMmNhLTRjZjktYmFjYi0zOTBkODI4Yzg0YjEifQ.82ZvIygphY_-rzdk_nEF48ZOgfhwhxWzIXTRNU8cnTU"

#Peticion 5: Mostrar Feed De Post De Amigos
curl -X GET http://localhost:8080/api/v1/friends/posts -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZWFkLWxpbmUiOiJTYXQgTWF5IDI5IDEwOjE0OjI4IDIwMjEiLCJpZCI6IjYwYjFjNDkyNGFiMjkzZGU5NjFkYTBlNyIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiY2ZhYnJpY2E0NiIsInV1aWQiOiI3OWVhOGVjNi0xMmNhLTRjZjktYmFjYi0zOTBkODI4Yzg0YjEifQ.82ZvIygphY_-rzdk_nEF48ZOgfhwhxWzIXTRNU8cnTU"
