#!/bin/bash

#Peticion 1: Mostrar Todos Los Usuario
#curl -X GET http://localhost:8080/users

#Peticion 2: Mostrar Todos Los Amigos De Un Usuario
#curl -X GET http://localhost:8080/user/friends -H "Authorization-header: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZWFkLWxpbmUiOiJTYXQgTWF5IDI5IDEwOjE0OjI4IDIwMjEiLCJpZCI6IjYwYjFjNDkyNGFiMjkzZGU5NjFkYTBlNyIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiY2ZhYnJpY2E0NiIsInV1aWQiOiI3OWVhOGVjNi0xMmNhLTRjZjktYmFjYi0zOTBkODI4Yzg0YjEifQ.82ZvIygphY_-rzdk_nEF48ZOgfhwhxWzIXTRNU8cnTU"

#Peticion 3: Mostrar Todos Los Post De Un Usuario
#curl -X GET http://localhost:8080/user/posts -H "Authorization-header: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZWFkLWxpbmUiOiJTYXQgTWF5IDI5IDEwOjE0OjI4IDIwMjEiLCJpZCI6IjYwYjFjNDkyNGFiMjkzZGU5NjFkYTBlNyIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiY2ZhYnJpY2E0NiIsInV1aWQiOiI3OWVhOGVjNi0xMmNhLTRjZjktYmFjYi0zOTBkODI4Yzg0YjEifQ.82ZvIygphY_-rzdk_nEF48ZOgfhwhxWzIXTRNU8cnTU"

#Peticion 4: Mostrar Post de un amigo
#curl -X GET http://localhost:8080/user/friend/posts -d '{"id":"60b1c4924ab293de961da0e8"}' -H "Authorization-header: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZWFkLWxpbmUiOiJTYXQgTWF5IDI5IDEwOjE0OjI4IDIwMjEiLCJpZCI6IjYwYjFjNDkyNGFiMjkzZGU5NjFkYTBlNyIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiY2ZhYnJpY2E0NiIsInV1aWQiOiI3OWVhOGVjNi0xMmNhLTRjZjktYmFjYi0zOTBkODI4Yzg0YjEifQ.82ZvIygphY_-rzdk_nEF48ZOgfhwhxWzIXTRNU8cnTU"

#Peticion 5: Mostrar Feed De Post De Amigos
#curl -X GET http://localhost:8080/user/friends/posts -H "Authorization-header: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZWFkLWxpbmUiOiJTYXQgTWF5IDI5IDEwOjE0OjI4IDIwMjEiLCJpZCI6IjYwYjFjNDkyNGFiMjkzZGU5NjFkYTBlNyIsInJvbGUiOiJhZG1pbiIsInVzZXJuYW1lIjoiY2ZhYnJpY2E0NiIsInV1aWQiOiI3OWVhOGVjNi0xMmNhLTRjZjktYmFjYi0zOTBkODI4Yzg0YjEifQ.82ZvIygphY_-rzdk_nEF48ZOgfhwhxWzIXTRNU8cnTU"
